### ISSUE TITLE
Unable to upload files bigger than 2 GB in ResumableMultipart mode

### ISSUE THREAD

**Issue by Belfegor1991** [f2calv/CasCap.Apis.GooglePhotos#111]
Uploading files with sizes more than 2 GB fails in **ResumableMultipart** mode with **JsonReaderException**:

> Error parsing Infinity value. Path '', line 1, position 2.

The reason is that variable **offset** in the method **GooglePhotosServiceBase.UploadMediaAsync** is **Int32**. As a result when loading files with sizes greater than **Int32.MaxValue**, **offset** overflows to a negative value passed to the HTTP header.

The solution would be to change the type of **offset** variable to **Int64**:

> var offset = 0L;

**Comment by f2calv** [comment]
Thanks for the alert+fix, I hope to roll this fix out in the next couple of days as part of https://github.com/f2calv/CasCap.Apis.GooglePhotos/pull/112
