### ISSUE TITLE
No permission to add media items to this album - When trying to upload to existing Album

### ISSUE THREAD

**Issue by vyshak-vijayan** [f2calv/CasCap.Apis.GooglePhotos#135]
Hello,

Thanks a lot for the .Net Wrapper :) .

 I recently came across an issue when trying to upload photos to existing google albums(created from Google Photos web UI/elsewhere) . I keep getting the following error 

`No permission to add media items to this album`

Even when the following permissions are granted in the Google security section

- Add to your Google Photos library
- View your Google Photos library 

I'm using version 1.1.2 of CasCap.Apis.GooglePhotos

Please advice

**Comment by f2calv** [comment]
Glad you find it useful!

Unfortunately it's a limitation of the API that you can only use the API to upload into an album that was actually created by the API itself.

You're not the first person to find yourself on the sharp edge of this issue... https://github.com/f2calv/CasCap.Apis.GooglePhotos/issues/118#issuecomment-1303828125

**Comment by vyshak-vijayan** [comment]
> Glad you find it useful!
> 
> Unfortunately it's a limitation of the API that you can only use the API to upload into an album that was actually created by the API itself.
> 
> You're not the first person to find yourself on the sharp edge of this issue... [#118 (comment)](https://github.com/f2calv/CasCap.Apis.GooglePhotos/issues/118#issuecomment-1303828125)

Thanks for the clarification.
