### ISSUE TITLE
MimeType support

### ISSUE THREAD

**Issue by ieei0214** [f2calv/CasCap.Apis.GooglePhotos#143]
Hello,

Thanks for the excellent .net library.

Try to upload the RW2 file which is supported by google photo but get System.NotSupportedException.

System.NotSupportedException: 'Cannot match file extension '.RW2' from 'd:/temp/GooglePhotos/P1000195.RW2' to a known image or video mime type.'

The AcceptedMimeTypesImage needs to include a more supported format.

```
    static readonly HashSet<string> AcceptedMimeTypesImage = new(StringComparer.OrdinalIgnoreCase)
    {
        { "image/bmp" },
        { "image/gif" },
        { "image/heic" },
        { "image/vnd.microsoft.icon" },
        { "image/jpeg" },
        { "image/jpeg" },
        { "image/png" },
        { "image/tiff" },
        { "image/webp" },
    };
```

**Comment by f2calv** [comment]
Thanks for raising the issue, this should be fixed with 2.0.2 now released, let me know if still issues... :)
