### ISSUE TITLE
How to find the owner of each media item? Otherwise is it possible to load only media items owned by user in shared album?

### ISSUE THREAD

**Issue by let92** [f2calv/CasCap.Apis.GooglePhotos#164]
Is it possible to know the owner of each media item, e.g. loaded by **GetMediaItemsByAlbumAsync** method, in Google Photos?

I mean, is there a property in some class?

I've found the property **contributorInfo** in class **MediaItem**, but, as written in summary, that field is only populated if the media item is in a shared album created by the app that use the library.

Do you confirm that is present only that property? Doesn't Google provide this useful information?

Otherwise, is it possible in method **GetMediaItemsByAlbumAsync** for a shared album to load only media items owned by the user used in the login?

I hope you can help me and thanks in advance.

**Comment by let92** [comment]
Any news?

**Comment by f2calv** [comment]
This class library is an implementation of the official API, I didn't write the original API so I cannot answer the question.
Please read the official API docs to get more clarity here, https://developers.google.com/photos/library/reference/rest/v1/sharedAlbums?hl=en
