### ISSUE TITLE
Feature: Login to support Cancellation

### ISSUE THREAD

**Issue by let92** [f2calv/CasCap.Apis.GooglePhotos#172]
Hi, it would be great to add **Cancellation** support to **Login method** because if user is not authorized to access Google APIs for the created program on Google API Console, the program will not receive any response from your library that calls Google's APIs and will endlessly wait for a response.

Like already done in https://github.com/f2calv/CasCap.Apis.GooglePhotos/issues/6 issue.

I hope you will develop this feature.

Thanks in advance.

Have a good day.

**Comment by let92** [comment]
Any news?

**Comment by f2calv** [comment]
> Any news?

fixed in latest release

**Comment by let92** [comment]
It's working perfectly, thank you very much!
