### ISSUE TITLE
File size by day and month

### ISSUE THREAD

**Issue by ga5tan** [f2calv/CasCap.Apis.GooglePhotos#55]
Hi

would it be possible to built an app with this library, that would calculate storage usage per Month and possibly per day for all the photos stored in the account?

something like 'du -sh *' in bash

**Comment by f2calv** [comment]
Unfortunately the Google Photos API doesn't return file size, it only returns;

- photo dimensions
- video resolution, frames per second

So you would need to either;

- download all the media items locally (or just to memory) and then store that information locally.
- extrapolate/estimate the file size based on the meta data (very inaccurate)

Then finally iterate over them to calculate out the total bytes used and use Linq to group by month/day/hour/etc...

**Comment by ga5tan** [comment]
oh man, that's what I was afraid of (from looking over it)
I guess there is no way to do any stats on photos itself? Android and web client are quite lame :(
