### ISSUE TITLE
Feature: GetMediaItem to support Cancellation

### ISSUE THREAD

**Issue by draoZA** [f2calv/CasCap.Apis.GooglePhotos#6]
Hi, would be great to add Cancellation support to (the long running) methods like _GetMediaItemsAsync. Could 
1) add optional CancellationToken
2) update while loop condition to (pageToken != null && !cancellationToken.IsCancellationRequested). Or similar.

see 
https://johnthiriet.com/cancel-asynchronous-operation-in-csharp/

Because if you accidentally tried to download the whole media library ... you might want to be able to cancel :-)

**Comment by f2calv** [comment]
All public methods which call the below _internal_ methods now have an optional cancellationToken parameter;

- _GetAlbumsAsync
- _GetMediaItemsAsync / _GetMediaItemsViaPOSTAsync
- _GetMediaItemsByFilterAsync

The updated NuGet should be available momentarily...

A good spot, and thanks for the positive feedback :)

**Comment by draoZA** [comment]
Thanks 😊

 

Von: Alex Vincent <notifications@github.com> 
Gesendet: Donnerstag, 20. August 2020 23:14
An: f2calv/CasCap.Apis.GooglePhotos <CasCap.Apis.GooglePhotos@noreply.github.com>
Cc: Lars <ldolling@gmx.net>; Author <author@noreply.github.com>
Betreff: Re: [f2calv/CasCap.Apis.GooglePhotos] Feature: GetMediaItem to support Cancellation (#6)

 

All public methods which call the below internal methods now have an optional cancellationToken parameter;

*	_GetAlbumsAsync
*	_GetMediaItemsAsync / _GetMediaItemsViaPOSTAsync
*	_GetMediaItemsByFilterAsync

The updated NuGet should be available momentarily...

A good spot, and thanks for the positive feedback :)

**Comment by draoZA** [comment]
Quick confirmation: Works perfect! 😊

 

Von: Alex Vincent <notifications@github.com> 
Gesendet: Donnerstag, 20. August 2020 23:14
An: f2calv/CasCap.Apis.GooglePhotos <CasCap.Apis.GooglePhotos@noreply.github.com>
Cc: Lars <ldolling@gmx.net>; Author <author@noreply.github.com>
Betreff: Re: [f2calv/CasCap.Apis.GooglePhotos] Feature: GetMediaItem to support Cancellation (#6)

 

All public methods which call the below internal methods now have an optional cancellationToken parameter;

*	_GetAlbumsAsync
*	_GetMediaItemsAsync / _GetMediaItemsViaPOSTAsync
*	_GetMediaItemsByFilterAsync

The updated NuGet should be available momentarily...

A good spot, and thanks for the positive feedback :)
