### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by vceklic** [f2calv/CasCap.Apis.GooglePhotos#8]
I have a big library with 10k+ items. When I run  _googlePhotosSvc.GetMediaItemsByAlbumAsync(album.id, 25); It take long time...hangs. What am I doing wrong since paging is not working for me. Could you please help? Also, is there a easy way to get filenames? Thanks.

**Comment by f2calv** [comment]
Firstly it depends on the number of mediaItems in your album - if you have thousands then yes it will take some time. Using the below code snippet it will only retrieve a maximum of 25 mediaItems each request (the Google API itself will decide the actual number of items returned) so in theory it could return any number of items between 1 and 25 and the wrapper will re-query for the next batch of 1->25 items;

```c#
var albumMediaItems = await _googlePhotosSvc.GetMediaItemsByAlbumAsync(album.id, 25);
```

For maximum speed the wrapper has a default batch size of 100, meaning you will get anywhere from 1->100 records in each call - so firstly either change 25 to 100 or as below just call without the pageSize parameter;
```c#
var albumMediaItems = await _googlePhotosSvc.GetMediaItemsByAlbumAsync(album.id);
```

To get additional feedback during the retrieval of (potentially large numbers of) records you should tie in the PagingEvent;
```c#
readonly GooglePhotosService _googlePhotosSvc;

public MyPhotoService(GooglePhotosService googlePhotosSvc)
{
    _googlePhotosSvc = googlePhotosSvc;
    _googlePhotosSvc.PagingEvent += _googlePhotosSvc_PagingEvent;
}

public void _googlePhotosSvc_PagingEvent(object sender, PagingEventArgs e)
{
    var str = $"Page {e.pageNumber}\t{e.recordCount}\t+{e.pageSize}";
    Console.WriteLine(str);
}
```

The first call I would advise making is `await _googlePhotosSvc.GetMediaItemsAsync()` (which in your case will get 10k items) and then prepare to cache/serialise that result so you don't have to call that again. That cached result is basically your entire library (incl filenames) and can be used as a lookup and/or the basis of making any further calls.

**Comment by vceklic** [comment]
Thanks Alex,
I expected to get back x number of Media Items, but it gets them all. Anyhow, it does work, but it takes time. Great work thanks.
