### ISSUE TITLE
Non Compatibilty with .Net Framework 4.5

### ISSUE THREAD

**Issue by vyshak-vijayan** [f2calv/CasCap.Apis.GooglePhotos#80]
Thanks a lot for your effort in creating a proper library for C#. Google API Documentation does not have any examples on consuming the their REST API in C#. 

I'm trying to use your library in one of my Winforms project that targets .net Framework 4.5. Installing from nuget does not seem to work since there is some compatibility issues with .Net 5. I have tried manually adding the DLLs but still there are some reference issues. Is there an official way to make this work with .Net Framework 4.5 ?

**Comment by f2calv** [comment]
The lowest target of the package is .NET Standard 2.0, however .NET Framework 4.5 is only compatible to .NET Standard at level 1.1, see https://docs.microsoft.com/en-us/dotnet/standard/net-standard for more detail.

This Google Photos package takes dependencies on other .NET Standard 2.0 packages so there really isn't much hope in getting this package to work in your current setup.

I believe your best hope is to update your WinForms app to target .NET Framework 4.6.1 or higher...
