### ISSUE TITLE
DownloadBytes does not preserve exif data

### ISSUE THREAD

**Issue by christiantsunami** [f2calv/CasCap.Apis.GooglePhotos#98]
It would be nice if the DownloadBytes would preserve the exif data, it currently does not, This can be accomplished by adding the "ip" parameter to the url you are creating to download the media item. (Found the info here https://gist.github.com/Sauerstoffdioxid/2a0206da9f44dde1fdfce290f38d2703)

https://github.com/f2calv/CasCap.Apis.GooglePhotos/blob/0c8f744a228f9985ea010f356d2d3adcd4525a19/src/CasCap.Apis.GooglePhotos/Services/GooglePhotosService.cs#L66

**Comment by f2calv** [comment]
Thanks for raising this, it would appear that my current implementation has an issue;

```csharp
if (downloadPhoto || qs.Count == 0) qs.Add("d");
```

According to [the docs](https://developers.google.com/photos/library/guides/access-media-items#base-urls) (search the page for 'EXIF') I should concatenate the baseUrl with `=d` except I'm adding it to the URL as a QueryString parameter instead.

I will have more time next week to look into this and run some tests and will update the library accordingly.

**Comment by pcartwright81** [comment]
This query looks good as shown by the screenshot with  baseUrl=d.  All my images downloaded from the API have EXIF metadata.
![image](https://user-images.githubusercontent.com/2352477/188293312-46f865be-6a6d-4d9b-a9fd-119a435874d2.png)
Adding -ip did not give a different result from what I can tell.  Location metadata is not available. 
![image](https://user-images.githubusercontent.com/2352477/188293879-d977a930-568d-4172-a14d-24d7523b511a.png)
Below are the list of the issues with the  Google Photos API gathered on another repo.
https://github.com/gilesknap/gphotos-sync/discussions/359

**Comment by f2calv** [comment]
So I added a bunch of EXIF tests [here](https://github.com/f2calv/CasCap.Apis.GooglePhotos/blob/main/src/CasCap.Apis.GooglePhotos.Tests/Tests/ExifTests.cs) and can confirm that the original query is correct.
Yes sadly Google strips the latitude/longitude data when the bytes are returned.
